name: Intall dependencies and run unit test

steps:
  - name: Set up Node.js
    run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

  - name: Use Node.js version
    uses: actions/setup-node@v3
    with:
      node-version: ${{ env.NODE_VERSION }}

  - uses: pnpm/action-setup@v2
    name: Install pnpm
    id: pnpm-install
    with:
      version: 8
      run_install: false

  - name: Get pnpm store directory
    id: pnpm-cache
    shell: bash
    run: |
      echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

  - uses: actions/cache@v3
    name: Setup pnpm cache
    with:
      path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-store-

  - name: Install dependencies
    run: pnpm install

  - name: Run unit tests
    run: pnpm run test
