name: Destroy
description: Remove the most recent deployment

runs:
  using: 'composite'
  steps:
    - name: Install Railway
      run: npm i -g @railway/cli
      shell: bash

    - name: Deploy
      run: railway down -y
      shell: bash
