name: Destroy
description: Remove the most recent deployment

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      shell: bash

    - name: Use Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Railway
      run: npm i -g @railway/cli
      shell: bash

    - name: Deploy
      run: railway down -y
      shell: bash
