name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Intall dependencies and run unit test
        uses: ./.github/actions/install

      - name: Deploy to production
        uses: ./.github/actions/deploy-railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
