name: Scheduled deployment

on:
  schedule:
    - cron: '0 1 * * *' # Schedule at 1:00 AM UTC

jobs:
  scheduled-deploy:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Intall dependencies and run unit test
        uses: ./.github/actions/install

      - name: Deploy to production
        uses: ./.github/actions/deploy-railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
